### ISSUE TITLE
Build libqdicteng.so from source using jni/ndk-build

### ISSUE THREAD

**Issue by ghost** [namndev/QDict#1]
Could you wire it up so that libqdicteng.so is build form source on compile-time? Or could you point me to the sourcecode for it?

**Comment by kuanyui** [comment]
+1

**Comment by marmistrz** [comment]
Can you please solve this? It blocks the app's inclusion into the F-Droid repository

**Comment by marmistrz** [comment]
libqdicteng.so has been removed in commit 4c04f86a49a6726179f60c082d4016fecdef338c

**Comment by ghost** [comment]
Thanks.

Ref: https://gitlab.com/fdroid/fdroiddata/merge_requests/1654
